using DataWarehouse.SDK.Contracts;
using DataWarehouse.SDK.Primitives;
using DataWarehouse.SDK.Security;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace DataWarehouse.SDK.Governance
{
    /// <summary>
    /// Represents an autonomous AI Agent capable of analyzing data events
    /// and issuing governance judgments (Security, Integrity, Organization).
    /// </summary>
    public interface INeuralSentinel : IPlugin
    {
        /// <summary>
        /// Evaluates a data operation context and determines if intervention is required.
        /// This is the primary entry point for all AI Governance logic.
        /// </summary>
        /// <param name="context">The context of the data operation (Who, What, When).</param>
        /// <returns>A judgment containing required actions, alerts, or modifications.</returns>
        Task<GovernanceJudgment> EvaluateAsync(SentinelContext context);
    }

    /// <summary>
    /// Contract for a pluggable intelligence unit within the Sentinel.
    /// </summary>
    public interface ISentinelModule
    {
        /// <summary>
        /// A unique identifier for this module (e.g., "PiiDetector").
        /// Used to map JSON commands to this module.
        /// </summary>
        string ModuleId { get; }

        /// <summary>
        /// Analyzes the context and returns a judgment.
        /// </summary>
        Task<GovernanceJudgment> AnalyzeAsync(SentinelContext context, IKernelContext kernel);
    }

    /// <summary>
    /// Defines the context in which the Sentinel is operating.
    /// </summary>
    public class SentinelContext
    {
        /// <summary>
        /// The event that triggered this evaluation.
        /// </summary>
        public TriggerType Trigger { get; set; }

        /// <summary>
        /// The metadata of the blob being acted upon.
        /// </summary>
        public Manifest Metadata { get; set; } = new();

        /// <summary>
        /// The raw data stream.
        /// NOTE: This may be null for Metadata-only scans or Delete operations.
        /// If present, the Sentinel must reset the position if it reads the stream.
        /// </summary>
        public Stream? DataStream { get; set; }

        /// <summary>
        /// The security context of the user/system initiating the action.
        /// </summary>
        public required ISecurityContext UserContext { get; set; }
    }

    /// <summary>
    /// The comprehensive decision returned by the Sentinel.
    /// The Kernel is responsible for enforcing these decisions.
    /// </summary>
    public class GovernanceJudgment
    {
        /// <summary>
        /// Indicates if the Kernel needs to take any action beyond the standard flow.
        /// If false, the Kernel proceeds normally.
        /// </summary>
        public bool InterventionRequired { get; set; }

        /// <summary>
        /// ACTION: Immediate Pipeline Override.
        /// Example: Sentinel detects PII -> Forces Encryption Pipeline.
        /// </summary>
        public PipelineConfig? EnforcePipeline { get; set; }

        /// <summary>
        /// ACTION: Block Operation.
        /// Example: Sentinel detects malware -> Deny Write.
        /// </summary>
        public bool BlockOperation { get; set; }

        /// <summary>
        /// ACTION: Modify Metadata.
        /// Example: Sentinel detects "Project X" content -> Adds "Project-X" tag.
        /// </summary>
        public List<string> AddTags { get; set; } = [];

        /// <summary>
        /// ACTION: Update specific Manifest properties.
        /// Key = Property Name, Value = New Value.
        /// </summary>
        public Dictionary<string, string> UpdateProperties { get; set; } = [];

        /// <summary>
        /// NOTIFICATION: Send an alert to the user or admin.
        /// </summary>
        public GovernanceAlert? Alert { get; set; }

        /// <summary>
        /// HEALING: Request the Kernel to restore this blob from a specific replica.
        /// Used for Bit Rot correction.
        /// </summary>
        public string? HealWithReplicaId { get; set; }
    }

    /// <summary>
    /// Helper result for legacy/specific integrity checks.
    /// Also used by exposed Sentinel Skills.
    /// </summary>
    public class GovernanceResult
    {
        public bool RiskDetected { get; set; }
        public required string RiskType { get; set; }
        public required string RecommendedAction { get; set; }
        public float Confidence { get; set; }
    }

    /// <summary>
    /// Represents a notification generated by the Sentinel.
    /// </summary>
    public class GovernanceAlert
    {
        /// <summary>
        /// The severity of the alert.
        /// </summary>
        public AlertSeverity Severity { get; set; }

        /// <summary>
        /// A code identifying the issue type (e.g., "PII_DETECTED", "INTEGRITY_FAIL").
        /// </summary>
        public string Code { get; set; } = string.Empty;

        /// <summary>
        /// The human-readable message.
        /// </summary>
        public string Message { get; set; } = string.Empty;

        /// <summary>
        /// Recommended remediation step for the user.
        /// </summary>
        public string Recommendation { get; set; } = string.Empty;
    }

    /// <summary>
    /// Helper result for legacy/specific integrity checks.
    /// </summary>
    public class IntegrityResult
    {
        public bool IsValid { get; set; }
        public string? CalculatedHash { get; set; }
        public string? ExpectedHash { get; set; }
    }

    /// <summary>
    /// Marks a method as an AI-accessible skill.
    /// The Neural Sentinel will auto-register this in the Agent's toolbox.
    /// </summary>
    /// <remarks>
    /// Defines a skill for the AI Agent.
    /// </remarks>
    /// <param name="name">Unique command name (e.g., "ScanPii").</param>
    /// <param name="description">Detailed prompt explaining WHEN and HOW to use this.</param>
    /// <param name="category">Grouping (Security, Integrity, Healing).</param>
    [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
    public class SentinelSkillAttribute(string name, string description, string category = "General") : Attribute
    {
        /// <summary>
        /// Name
        /// </summary>
        public string Name { get; } = name;

        /// <summary>
        /// Description
        /// </summary>
        public string Description { get; } = description;

        /// <summary>
        /// Category
        /// </summary>
        public string Category { get; } = category;
    }

    /// <summary>
    /// Describes a parameter for an AI skill.
    /// Used to generate strict JSON schemas for the LLM.
    /// </summary>
    [AttributeUsage(AttributeTargets.Parameter, Inherited = false, AllowMultiple = false)]
    public class SentinelParameterAttribute(string description, string example = "", bool isRequired = true) : Attribute
    {
        public string Description { get; } = description;
        public string Example { get; } = example;
        public bool IsRequired { get; } = isRequired;
    }
}